from typing import Dict

TABLE_SCHEMAS: Dict[str, Dict] = {
    
"IVINSPECTIONHISTORY": {
  "description": "Inventory or item  Inspection transaction History .",
  "columns": {
    "Company": "VARCHAR2(10)-",
    "Company Name": "VARCHAR2(200)",
    "HPL Description": "VARCHAR2(200)",
    "House Product Line": "VARCHAR2(20)",
    "INSPECTION_TEXT": "CLOB - Inspection notes text",
    "Item Commodity": "VARCHAR2(20)",
    "ITEM_DESCRIPTION": "VARCHAR2(500)",
    "European Article Number (EAN)": "VARCHAR2(50)",
    "End of Life": "DATE",
    "Expanded EAN": "VARCHAR2(50)",
    "Item Forecast Group Code": "VARCHAR2(20)",
    "Freight Class": "VARCHAR2(20)",
    "Item Hazard": "VARCHAR2(20)",
    "Item House Product Line": "VARCHAR2(20)",
    "Item": "VARCHAR2(50)",
    "Material Specifications": "VARCHAR2(500)",
    "Military Specification": "VARCHAR2(500)",
    "Item Modification Date": "DATE",
    "Company Item Product Code": "VARCHAR2(50)",
    "Item Planner": "VARCHAR2(50)",
    "Primary CCN": "VARCHAR2(10)",
    "PSI Item": "VARCHAR2(50)",
    "Item Responsible Person": "VARCHAR2(100)",
    "Revision": "VARCHAR2(20)",
    "Setup Date": "DATE",
    "Item Type": "VARCHAR2(20)",
    "Item Unique ID": "VARCHAR2(50)",
    "Universal Product Code": "VARCHAR2(50)",
    "Company Item AGC": "VARCHAR2(20)",
    "Company Item Analyst": "VARCHAR2(20)",
    "Blanket Order Line": "NUMBER",
    "Company Item Blanket Order": "VARCHAR2(20)",
    "Buying UM": "VARCHAR2(10)",
    "Company Item Buyer": "VARCHAR2(50)",
    "Item Company": "VARCHAR2(10)",
    "Critical": "VARCHAR2(1)",
    "Delivery Purchase Location": "VARCHAR2(20)",
    "Company Item Supplier": "VARCHAR2(20)",
    "Company Item Delete": "VARCHAR2(1)",
    "Delivery Policy": "VARCHAR2(20)",
    "Demand Fence": "NUMBER",
    "Company Item Division": "VARCHAR2(20)",
    "Drawing Date": "DATE",
    "Drawing Revision": "VARCHAR2(20)",
    "Drawing Size": "VARCHAR2(10)",
    "Drawing": "VARCHAR2(100)",
    "ECN": "VARCHAR2(50)",
    "ECN Pending": "VARCHAR2(1)",
    "ECN Date": "DATE",
    "Finished Good": "VARCHAR2(1)",
    "Floor Stock": "VARCHAR2(1)",
    "Company Item Halt Reason": "VARCHAR2(20)",
    "Company Item": "VARCHAR2(50)",
    "Primary Location": "VARCHAR2(20)",
    "Make": "VARCHAR2(1)",
    "Company Item Make to Stock": "VARCHAR2(1)",
    "Service Manufacturer": "VARCHAR2(100)",
    "Mast Sched": "VARCHAR2(1)",
    "Material Supply": "VARCHAR2(20)",
    "Company Item Mfg. Group": "VARCHAR2(20)",
    "Manufacturing Engineer": "VARCHAR2(50)",
    "Obsolete": "VARCHAR2(1)",
    "Obsoleted On": "DATE",
    "Country of Origin": "VARCHAR2(10)",
    "Phantom": "VARCHAR2(1)",
    "Primary Country": "VARCHAR2(10)",
    "Company Item Purchase Company": "VARCHAR2(10)",
    "Supplier Location": "VARCHAR2(20)",
    "Receiving QA Status": "VARCHAR2(10)",
    "Company Item Revision": "VARCHAR2(20)",
    "Scrap Percent": "NUMBER(10,4)",
    "Group": "VARCHAR2(20)",
    "Serial Control": "VARCHAR2(1)",
    "Serial Assigned": "VARCHAR2(1)",
    "Shelf Life": "NUMBER",
    "Company Item Stocking Line": "VARCHAR2(20)",
    "Spares": "VARCHAR2(1)",
    "Specification ID": "VARCHAR2(50)",
    "Standard Lot Size": "NUMBER",
    "Company Item Stock Status": "VARCHAR2(20)",
    "Company Item Stock UM": "VARCHAR2(10)",
    "Primary Supplier": "VARCHAR2(20)",
    "Vendor Product Line": "VARCHAR2(20)",
    "Accepted Quantity": "NUMBER(18,4)",
    "Item Inspection Company": "VARCHAR2(10)",
    "Inspected On": "DATE - Date when the inspection was performed. If specific date is not mentioned, use this column as reference ",
    "Inspected By": "VARCHAR2(50)",
    "Inspection Item": "VARCHAR2(50)",
    "Inspection Report": "VARCHAR2(50)",
    "Item Inspection Lot": "VARCHAR2(50)",
    "Insp Item Lot/Serial Company": "VARCHAR2(10)",
    "Item Inspection ML": "VARCHAR2(20)",
    "Item Inspection Pur Location": "VARCHAR2(20)",
    "Inspected Qty": "NUMBER(18,4)",
    "Item Inspection Reason": "VARCHAR2(50)",
    "Alpha Date Received": "DATE",
    "Date Received": "DATE",
    "Item Inspection Receiver Line": "NUMBER",
    "RECEIPT_QUANTITY": "NUMBER(18,4)",
    "Time Received": "VARCHAR2(20)",
    "Item Inspection Receiver": "VARCHAR2(50)",
    "Inspection Reference": "VARCHAR2(50)",
    "Inspection Reference CCN": "VARCHAR2(10)",
    "Purchase Order Release": "VARCHAR2(20)",
    "Rejected Quantity": "NUMBER(18,4)",
    "Inspection Item Revision": "VARCHAR2(20)",
    "Inspection Item Serial": "VARCHAR2(50)",
    "Reference Type": "VARCHAR2(20)",
    "INSPECTED_TIME": "VARCHAR2(20)",
    "Vendor": "VARCHAR2(20)",
    "Master Location Name": "VARCHAR2(200)",
    "ML": "VARCHAR2(20)",
    "PC Description": "VARCHAR2(200)",
    "Gross Margin Percentage": "NUMBER(10,4)",
    "Product Code": "VARCHAR2(20)",
    "Vendor Purchase Company": "VARCHAR2(10)",
    "Hold Reason": "VARCHAR2(200)",
    "Pay on Use": "VARCHAR2(1)",
    "Purchase Location": "VARCHAR2(20)",
    "Supplier Location QA Status": "VARCHAR2(20)",
    "Quality Rating": "NUMBER(10,2)"
  }
},
"ITRN_HISTORY_VW": {
   "description": "item inventory transaction history.",
    "columns": {
        "Company Code": "VARCHAR2(10)",
        "Master Location": "VARCHAR2",
        "Item Number": "VARCHAR2(50)",
        "Item Revision": "VARCHAR2(10)",
        "Transaction Date": "DATE -  Date when the inventory transaction occurred. If specific date is not mentioned, use this column as the reference .",
        "Terminal ID": "VARCHAR2",
        "Transaction Time": "VARCHAR2",
        "Transaction Sequence": "NUMBER",
        "Source Type": "VARCHAR2",
        "Source Qualifier": "VARCHAR2",
        "Reference Number": "VARCHAR2",
        "Reference Line": "NUMBER",
        "Consumable Flag": "VARCHAR2(1)",
        "AGC Code": "VARCHAR2",
        "GL Account": "VARCHAR2",
        "Location Code": "VARCHAR2(20)",
        "Bin Code": "VARCHAR2",
        "Lot Number": "VARCHAR2",
        "Lot/Serial Company": "VARCHAR2(10)",
        "Purchase Company": "VARCHAR2(10)",
        "Receiver Number": "VARCHAR2",
        "Receiver Line": "NUMBER",
        "Vendor Number": "VARCHAR2",
        "Purchase Location": "VARCHAR2",
        "Buy/Sell Cost": "NUMBER",
        "New Average Cost": "NUMBER",
        "Old Average Cost": "NUMBER",
        "Quantity": "NUMBER",
        "User ID": "VARCHAR2",
        "Posting Date": "DATE",
        "Transaction Cost": "NUMBER",
        "RP Schedule": "VARCHAR2",
        "Inspection Status": "VARCHAR2",
        "MRB Disposition": "VARCHAR2",
        "Onhand Qty Before Adj": "NUMBER",
        "Adjusted Frozen Qty": "NUMBER",
        "From/To Company": "VARCHAR2(10)",
        "From/To Location": "VARCHAR2",
        "Reason Code": "VARCHAR2",
        "Process ID": "VARCHAR2",
        "ML Available Qty": "NUMBER",
        "Local Date": "DATE",
        "Local Time": "VARCHAR2",
        "GMT Offset": "NUMBER",
        "User Alpha 1": "VARCHAR2",
        "User Alpha 2": "VARCHAR2",
        "User Alpha 3": "VARCHAR2",
        "User Num 1": "NUMBER",
        "User Num 2": "NUMBER",
        "User Num 3": "NUMBER",
        "User Date": "DATE",
        "User Time": "VARCHAR2",
        "Seiban Number": "VARCHAR2",
        "WO Operation Scrap Seq": "NUMBER"
    }
},
"IVONHANDBYLOCATION": {
    "description": "Inventory on hand by location .",
    "columns": {
        "COST_AS_OF_DATE": "VARCHAR2 - Date when the cost was last updated. If specific date is not mentioned, use this column as reference for the inventory on hand data.",
        "Cost Item": "VARCHAR2",
        "Cost Item Revision": "VARCHAR2",
        "Error at Lower Level": "VARCHAR2",
        "Error at this Level": "VARCHAR2",
        "BCR_ALT": "VARCHAR2",
        "Item Cost Company": "VARCHAR2(10)",
        "Item Cost Description": "VARCHAR2",
        "BCR_TYPE": "VARCHAR2",
        "Item has Opercosts": "VARCHAR2",
        "Labor Run Hours": "NUMBER",
        "Labor Setup Hours": "NUMBER",
        "Machine Run Hours": "NUMBER",
        "Machine Setup Hours": "NUMBER",
        "MANUAL_COST": "VARCHAR2",
        "Material Cost Center": "VARCHAR2",
        "Roll up Date": "VARCHAR2",
        "Scrap Percentage": "NUMBER",
        "Company Item Product Code": "VARCHAR2(20)",
        "End of Life": "DATE",
        "ENG Conf Odom": "VARCHAR2",
        "European Article Number (EAN)": "VARCHAR2(50)",
        "Expanded EAN": "VARCHAR2",
        "Freight Class": "VARCHAR2",
        "Height": "NUMBER",
        "Item": "VARCHAR2(50)",
        "Item Commodity": "VARCHAR2(20)",
        "Item Delete": "VARCHAR2(1)",
        "ITEM_DESCRIPTION": "VARCHAR2(500)",
        "Item Division": "VARCHAR2(20)",
        "Item Forecast Group Code": "VARCHAR2(20)",
        "Item Group Technology Code": "VARCHAR2(20)",
        "Item Hazard": "VARCHAR2(20)",
        "Item Height UM": "VARCHAR2(10)",
        "Item House Product Line": "VARCHAR2(20)",
        "Item Length UM": "VARCHAR2(10)",
        "Item Modification Date": "VARCHAR2",
        "Item Planner": "VARCHAR2(20)",
        "Item Responsible Person": "VARCHAR2",
        "Item Type": "VARCHAR2(20)",
        "Item Unique ID": "NUMBER",
        "Item Weight UM": "VARCHAR2(10)",
        "Item Width UM": "VARCHAR2(10)",
        "ITEM_EC_PREFIX": "VARCHAR2",
        "Length": "NUMBER",
        "Material Specifications": "VARCHAR2",
        "Military Specification": "VARCHAR2",
        "Primary CCN": "VARCHAR2(10)",
        "PSI Item": "VARCHAR2",
        "Record ID": "VARCHAR2",
        "Revision": "VARCHAR2(10)",
        "Setup Date": "VARCHAR2",
        "Test Last Sequence": "NUMBER",
        "Universal Product Code": "VARCHAR2(50)",
        "User Sort Seq": "VARCHAR2",
        "Weight": "NUMBER",
        "Width": "NUMBER",
        "Auto Requisition Status": "VARCHAR2",
        "Automatic Work Order": "VARCHAR2",
        "Avail To Promise": "VARCHAR2",
        "Blanket Order Line": "NUMBER",
        "Buying UM": "VARCHAR2(10)",
        "Company Item": "VARCHAR2(50)",
        "Company Item ABC": "VARCHAR2(20)",
        "COMPANY_ITEM_AGC": "VARCHAR2",
        "Company Item Analyst": "VARCHAR2(20)",
        "Company Item Blanket Order": "VARCHAR2",
        "Company Item Buyer": "VARCHAR2(20)",
        "Company Item Consume IV": "VARCHAR2",
        "Company Item Conv Tolerance": "NUMBER",
        "Company Item Delete": "VARCHAR2(1)",
        "Company Item Division": "VARCHAR2(20)",
        "Company Item Drop Ship": "VARCHAR2",
        "Company Item Halt Reason": "VARCHAR2(20)",
        "Company Item Make to Stock": "VARCHAR2",
        "Company Item Mfg. Group": "VARCHAR2",
        "COMPANY_ITEM_MODIFICATION_DATE": "VARCHAR2",
        "Company Item MRP Planned": "VARCHAR2",
        "Company Item Order Quantity": "NUMBER",
        "Company Item Policy Code": "VARCHAR2",
        "Company Item Price Code": "VARCHAR2",
        "Company Item PRP Flag": "VARCHAR2",
        "Company Item Purchase Company": "VARCHAR2(10)",
        "Company Item Receipt Tolerance": "NUMBER",
        "Company Item Resp Person": "VARCHAR2",
        "Company Item Revision": "VARCHAR2(10)",
        "Company Item Sales Taxable": "VARCHAR2",
        "Company Item Selling UM": "VARCHAR2(10)",
        "COMPANY_ITEM_STOCK_STATUS": "VARCHAR2",
        "COMPANY_ITEM_STOCK_UM": "VARCHAR2(10)",
        "Company Item Stocking Line": "VARCHAR2",
        "Company Item Supplier": "VARCHAR2",
        "Company Item Tariff Code": "VARCHAR2",
        "Company Item Tolerance Code": "VARCHAR2",
        "Company Item Type": "VARCHAR2",
        "Company Item Unique ID": "NUMBER",
        "Company Item Usage Taxable": "VARCHAR2",
        "Company Item VAT Code": "VARCHAR2",
        "Company Item Voucher Tolerance": "NUMBER",
        "Consume Forecast": "VARCHAR2",
        "Contract Item": "VARCHAR2",
        "Conv CPOs to Rep": "VARCHAR2",
        "COST_METHOD": "VARCHAR2(3)",
        "Country of Origin": "VARCHAR2(10)",
        "CPO Auto Conv Type": "VARCHAR2",
        "Critical": "VARCHAR2",
        "Delivery Policy": "VARCHAR2",
        "Delivery Purchase Location": "VARCHAR2",
        "Demand Bucket": "NUMBER",
        "Demand Fence": "NUMBER",
        "Direct Cost": "VARCHAR2",
        "Dock to Stock": "NUMBER",
        "Drawing": "VARCHAR2",
        "DRAWING_DATE": "VARCHAR2",
        "Drawing Revision": "VARCHAR2",
        "Drawing Size": "VARCHAR2",
        "DTS Lead Time Unit": "VARCHAR2",
        "ECN": "VARCHAR2",
        "ECN_DATE": "VARCHAR2",
        "ECN Pending": "VARCHAR2",
        "Expensed": "VARCHAR2",
        "Fence": "NUMBER",
        "Finished Good": "VARCHAR2",
        "Fixed": "NUMBER",
        "Fixed Lead Time Unit": "VARCHAR2",
        "FLOOR_STOCK": "VARCHAR2",
        "Freeze Period": "NUMBER",
        "Group": "VARCHAR2",
        "Installation Group": "VARCHAR2",
        "Item Company": "VARCHAR2(10)",
        "Item Country of Dispatch": "VARCHAR2(10)",
        "Item Quantity Price Code": "VARCHAR2",
        "Item Update Sales Analysis": "VARCHAR2",
        "Latest Revision": "VARCHAR2(10)",
        "LEADTIME_ROLLUP_AS_OF_DATE": "VARCHAR2",
        "Lot Control": "VARCHAR2",
        "Lot Level": "VARCHAR2",
        "Low Level Code": "NUMBER",
        "LS Prefix": "VARCHAR2",
        "PLAN_TYPE": "VARCHAR2(4)",
        "Manufacturing Engineer": "VARCHAR2(20)",
        "Mast Sched": "VARCHAR2",
        "Material Supply": "VARCHAR2",
        "Maximum Stock": "NUMBER",
        "Minimum Stock": "NUMBER",
        "Net Avail Code": "VARCHAR2",
        "Obsolete": "VARCHAR2",
        "Obsoleted On": "DATE",
        "Order Point": "NUMBER",
        "Order Policy": "VARCHAR2",
        "Order Preparation": "NUMBER",
        "Order Quantity Multiple": "NUMBER",
        "Order Rule": "VARCHAR2",
        "Order Size": "NUMBER",
        "Pack Qty": "NUMBER",
        "Phantom": "VARCHAR2",
        "Planning Fence": "NUMBER",
        "Policy Days": "NUMBER",
        "Populate Multilevel Site Regis": "VARCHAR2",
        "Preparation Lead Time Unit": "VARCHAR2",
        "Primary Country": "VARCHAR2(10)",
        "Primary Location": "VARCHAR2(20)",
        "Primary Supplier": "VARCHAR2",
        "Product Release": "VARCHAR2",
        "PRP ML": "VARCHAR2",
        "Pull Cycle": "NUMBER",
        "Receiving QA Status": "VARCHAR2",
        "Repetitive": "VARCHAR2",
        "Replenish": "VARCHAR2",
        "Requisition Lead Time": "NUMBER",
        "Requisition Lead Time Unit": "VARCHAR2",
        "Requisition Required": "VARCHAR2",
        "Review Cycle": "NUMBER",
        "Safety Stock": "NUMBER",
        "Safety Stock Lead Time Unit": "VARCHAR2",
        "Safety Stock Quantity": "NUMBER",
        "Sales - ATP": "NUMBER",
        "Sales Lead Time Unit": "VARCHAR2",
        "Scrap Percent": "NUMBER",
        "Serial Assigned": "VARCHAR2",
        "Serial Control": "VARCHAR2",
        "Service Manufacturer": "VARCHAR2",
        "Service Repair Count": "NUMBER",
        "Shelf Life": "NUMBER",
        "Ship Prep Lead Time Unit": "VARCHAR2",
        "Shipping Preparation": "NUMBER",
        "Spares": "VARCHAR2",
        "Specification ID": "VARCHAR2",
        "SR Item Price Code": "VARCHAR2",
        "Standard Cost": "NUMBER",
        "Standard Lot Size": "NUMBER",
        "Supplier Location": "VARCHAR2",
        "Unit Type": "VARCHAR2",
        "Variable": "NUMBER",
        "Variable Lead Time Unit": "VARCHAR2",
        "VAT Group": "VARCHAR2",
        "Vendor Product Line": "VARCHAR2",
        "Bin Item Out": "VARCHAR2",
        "ITEM_DETAIL_INSPECTION": "VARCHAR2",
        "ITEM_DETAIL_BIN": "VARCHAR2",
        "ITEM_DETAIL_COMMITTED_QUANTITY": "NUMBER",
        "ITEM_DETAIL_COMPANY": "VARCHAR2(10)",
        "ITEM_DET_ITEM": "VARCHAR2(50)",
        "ITEM_DETAIL_LOCATION": "VARCHAR2(20)",
        "ITEM_DETAIL_LOT": "VARCHAR2",
        "ITEM_DETAIL_LOT_SERIAL_COMPANY": "VARCHAR2(10)",
        "ITEM_DETAIL_ML": "VARCHAR2",
        "ITEM_DETAIL_MRB": "VARCHAR2",
        "ITEM_DETAIL_REVISION": "VARCHAR2(10)",
        "ITEM_DETAIL_SERIAL": "VARCHAR2",
        "ITEM_RESERVED_QUANTITY": "NUMBER",
        "Last Sequence": "NUMBER",
        "NETTABLE": "NUMBER",
        "Suppliers Document": "VARCHAR2",
        "ITEM_DETAIL_ON_HAND_QUANTITY": "NUMBER",
        "Average Cost": "NUMBER",
        "Beg Dep Demands": "NUMBER",
        "Beg Ind Demands": "NUMBER",
        "Beg Reserved Qty": "NUMBER",
        "Begin Dependent Demand Qty": "NUMBER",
        "Beginning Committed Quantity": "NUMBER",
        "Beginning Mfg. Supply Quantity": "NUMBER",
        "Beginning On Hand Quantity": "NUMBER",
        "Beginning Purchase Supply Qty": "NUMBER",
        "Count Date": "VARCHAR2",
        "Dep Demands": "NUMBER",
        "Dependent Demand Quantity": "NUMBER",
        "Inactive Periods": "NUMBER",
        "Ind Demands": "NUMBER",
        "Independent Begin Demand Qty": "NUMBER",
        "Independent Demand Issue": "NUMBER",
        "Independent Demand Quantity": "NUMBER",
        "Independent Issue": "NUMBER",
        "Item Master Location Company": "VARCHAR2(10)",
        "Item ML": "VARCHAR2",
        "Item ML Committed Quantity": "NUMBER",
        "Item ML On Hand Quantity": "NUMBER",
        "Manufacturing Supply Quantity": "NUMBER",
        "Master Location Item": "VARCHAR2(50)",
        "Master Location Item Revision": "VARCHAR2(10)",
        "ML  Sum Item Quantity": "NUMBER",
        "ML Purchase Supply Quantity": "NUMBER",
        "No of Receipts": "NUMBER",
        "Non Nettable Quantity": "NUMBER",
        "Per Cyc Counts": "NUMBER",
        "Period Adj": "NUMBER",
        "Period Adjusted Quantity": "NUMBER",
        "Period Cycle Adj": "NUMBER",
        "Period Cycle Adjusted Quantity": "NUMBER",
        "Period Dep Dem Issues": "NUMBER",
        "Period Dependent Demand Issue": "NUMBER",
        "Period Ind Demand Iss": "NUMBER",
        "Period Mfg Receipt Quantity": "NUMBER",
        "Period Mfg Receipts": "NUMBER",
        "Period PI Adj": "NUMBER",
        "Period PI Adjustment": "NUMBER",
        "Period PI Counts": "NUMBER",
        "Period Purch Receipts": "NUMBER",
        "Period Purchase Receipt Qty": "NUMBER",
        "Period Scrap Quantity": "NUMBER",
        "Period Scraps": "NUMBER",
        "Period Trans Ins": "NUMBER",
        "Period Trans Outs": "NUMBER",
        "Period Transaction In Quantity": "NUMBER",
        "Period Transaction Out Qty": "NUMBER",
        "Physical Inventory Date": "VARCHAR2",
        "PI Counts": "NUMBER",
        "Primary FA Location": "VARCHAR2",
        "Primary Rep WC Location": "VARCHAR2",
        "Reserved Quantity": "NUMBER",
        "Total Item Cost1": "NUMBER",
        "Total Item Cost2": "NUMBER",
        "Total Item Cost3": "NUMBER",
        "Total Item Cost4": "NUMBER",
        "Total Item Cost5": "NUMBER",
        "Total Item Cost6": "NUMBER",
        "Total Item Cost7": "NUMBER",
        "Total Item Cost8": "NUMBER",
        "Total Item Cost9": "NUMBER",
        "Total Item Cost10": "NUMBER",
        "Total Item Cost11": "NUMBER",
        "Total Item Cost12": "NUMBER",
        "Total Item Cost13": "NUMBER",
        "Total Item Cost14": "NUMBER",
        "Total Item Cost15": "NUMBER",
        "Total Item Cost16": "NUMBER",
        "Total Item Cost17": "NUMBER",
        "Total Item Cost18": "NUMBER",
        "Total Item Cost19": "NUMBER",
        "Total Item Cost20": "NUMBER",
        "Total Item Cost21": "NUMBER",
        "Total Item Cost22": "NUMBER",
        "Total Item Cost23": "NUMBER",
        "Total Item Cost24": "NUMBER",
        "Year to Date Adjusted Quantity": "NUMBER",
        "Year to Date Counts": "NUMBER",
        "Year to Date Cycle Adjusted Qu": "NUMBER",
        "Year to Date Dependent Demand": "NUMBER",
        "Year to Date PI Adjusted Quant": "NUMBER",
        "Year to Date Scrap Quantity": "NUMBER",
        "Year to Date Transaction Out Q": "NUMBER",
        "YTD Adj": "NUMBER",
        "YTD Cycle Adj": "NUMBER",
        "YTD Dep Demand Iss": "NUMBER",
        "YTD Ind Demand Iss Qty": "NUMBER",
        "YTD Mfg Receipt Quantity": "NUMBER",
        "YTD Mfg Receipts": "NUMBER",
        "YTD PI Adj": "NUMBER",
        "YTD Purch Receipts": "NUMBER",
        "YTD Purchase Receipt Quantity": "NUMBER",
        "YTD Scraps": "NUMBER",
        "YTD Trans In Qty": "NUMBER",
        "YTD Trans Ins": "NUMBER",
        "YTD Trans Outs": "NUMBER",
        "Cost Updated": "VARCHAR2",
        "Lot": "VARCHAR2",
        "Lot  Item Country Origin": "VARCHAR2(10)",
        "Lot Item": "VARCHAR2(50)",
        "Lot Item  Received Quantity": "NUMBER",
        "Lot Item Actual Cost": "NUMBER",
        "Lot Item Country Dispatch": "VARCHAR2(10)",
        "Lot Item Purchase Company": "VARCHAR2(10)",
        "Lot Item Purchase Location": "VARCHAR2",
        "Lot Item Receiver": "VARCHAR2",
        "Lot Item Receiving Line": "NUMBER",
        "Lot Item Receiving QA Status": "VARCHAR2",
        "Lot Item Revision": "VARCHAR2(10)",
        "Lot Item Tariff": "VARCHAR2",
        "Lot Item Trade Group Dispatch": "VARCHAR2",
        "Lot Item Trade Group Origin": "VARCHAR2",
        "Lot Item UM": "VARCHAR2(10)",
        "Lot Reference": "VARCHAR2",
        "Lot Reference Line": "NUMBER",
        "Lot Source": "VARCHAR2",
        "Lot Supplier": "VARCHAR2",
        "Lot/Serial Company": "VARCHAR2(10)",
        "Receipt ML": "VARCHAR2",
        "Received on": "VARCHAR2",
        "Shelf End of Life": "DATE",
        "COMPANY_NAME": "VARCHAR2(200)",
        "CCN_CURRENCY": "VARCHAR2(10)",
        "MASTER_LOCATION_NAME": "VARCHAR2(200)",
        "LOCATION_NAME": "VARCHAR2(200)",
        "ITEM_COST1": "NUMBER",
        "ITEM_COST2": "NUMBER",
        "ITEM_COST3": "NUMBER",
        "ITEM_COST4": "NUMBER",
        "ITEM_COST5": "NUMBER",
        "ITEM_COST6": "NUMBER",
        "ITEM_COST7": "NUMBER",
        "ITEM_COST8": "NUMBER",
        "ITEM_COST9": "NUMBER",
        "ITEM_COST10": "NUMBER",
        "ITEM_COST11": "NUMBER",
        "ITEM_COST12": "NUMBER",
        "ITEM_COST13": "NUMBER",
        "ITEM_COST14": "NUMBER",
        "ITEM_COST15": "NUMBER",
        "ITEM_COST16": "NUMBER",
        "ITEM_COST17": "NUMBER",
        "ITEM_COST18": "NUMBER",
        "ITEM_COST19": "NUMBER",
        "ITEM_COST20": "NUMBER",
        "ITEM_COST21": "NUMBER",
        "EXTENDED_AMOUNT": "NUMBER",
        "COST_DESCRIPTION1": "VARCHAR2",
        "COST_DESCRIPTION2": "VARCHAR2",
        "COST_DESCRIPTION3": "VARCHAR2",
        "COST_DESCRIPTION4": "VARCHAR2",
        "COST_DESCRIPTION5": "VARCHAR2",
        "COST_DESCRIPTION6": "VARCHAR2",
        "COST_DESCRIPTION7": "VARCHAR2",
        "COST_DESCRIPTION8": "VARCHAR2",
        "COST_DESCRIPTION9": "VARCHAR2",
        "COST_DESCRIPTION10": "VARCHAR2",
        "COST_DESCRIPTION11": "VARCHAR2",
        "COST_DESCRIPTION12": "VARCHAR2",
        "COST_DESCRIPTION13": "VARCHAR2",
        "COST_DESCRIPTION14": "VARCHAR2",
        "COST_DESCRIPTION15": "VARCHAR2",
        "COST_DESCRIPTION16": "VARCHAR2",
        "COST_DESCRIPTION17": "VARCHAR2",
        "COST_DESCRIPTION18": "VARCHAR2",
        "COST_DESCRIPTION19": "VARCHAR2",
        "COST_DESCRIPTION20": "VARCHAR2",
        "COST_DESCRIPTION21": "VARCHAR2",
        "LOCATION_CONSIGNED": "VARCHAR2"
    }
},

    "XV_REC_HIS_VW": {
    "description": "Receiver transaction history .",
    "columns": {
        "Company Code": "VARCHAR2",
        "Master Location": "VARCHAR2",
        "Receiver Number": "VARCHAR2",
        "Receiver Line": "NUMBER",
        "Received Date": "DATE - DATE - Date when the receipt was processed. if doesnt mentione specfic date use this like last 6 months data",
        "Packing Slip": "VARCHAR2",
        "Vendor Code": "VARCHAR2",
        "Purchasing Location": "VARCHAR2",
        "Vendor Location Name": "VARCHAR2",
        "Item Number": "VARCHAR2",
        "Item Revision": "VARCHAR2",
        "Item Description": "VARCHAR2",
        "Purchasing Company Code": "VARCHAR2",
        "Account Group Code": "VARCHAR2",
        "General Ledger Account": "VARCHAR2",
        "Lot Company Code": "VARCHAR2",
        "Lot Number": "VARCHAR2",
        "Order Type": "VARCHAR2",
        "Order Number": "VARCHAR2",
        "Order Line": "NUMBER",
        "Qa Status": "VARCHAR2",
        "Currency Code": "VARCHAR2",
        "Buy Unit Of Measure": "VARCHAR2",
        "Buy Quantity": "NUMBER",
        "Buy Unit Price": "NUMBER",
        "Stock Unit Of Measure": "VARCHAR2",
        "Stock Quantity": "NUMBER",
        "Stock Unit Price": "NUMBER",
        "Open Voucher Quantity": "NUMBER",
        "Invoice Unit Cost": "NUMBER",
        "Ppv Amount": "NUMBER",
        "Voucher Quantity": "NUMBER",
        "Over Receipt Quantity": "NUMBER",
        "Stockroom": "VARCHAR2",
        "Sales Company Code": "VARCHAR2",
        "Accounts Payable Company Code": "VARCHAR2",
        "Voucher Date": "DATE",
        "Buyer Code": "VARCHAR2",
        "Location Code": "VARCHAR2",
        "Bin Location": "VARCHAR2",
        "Unit Measure Scalar": "NUMBER",
        "Exception Message": "VARCHAR2",
        "Reversed Quantity": "NUMBER",
        "Last Detail Sequence": "NUMBER",
        "Book Rate": "NUMBER",
        "Book Rate Divisor": "NUMBER",
        "Order Book Rate": "NUMBER",
        "Order Book Rate Divisor": "NUMBER",
        "Tariff Code": "VARCHAR2",
        "Origin Country": "VARCHAR2",
        "Duty Rate Insurance Percent": "NUMBER",
        "Duty Rate Misc Percent": "NUMBER",
        "Voucher Tolerance": "NUMBER",
        "Taxable Flag": "VARCHAR2",
        "Last Issue Sequence": "NUMBER",
        "Net Actual Cost Calc Flag": "VARCHAR2",
        "Inspected Quantity": "NUMBER",
        "Accepted Quantity": "NUMBER",
        "Rejected Quantity": "NUMBER",
        "Accepted Date": "DATE",
        "Rejected Date": "DATE",
        "Reversal Reason": "VARCHAR2",
        "Way Match Flag": "VARCHAR2",
        "Last Inspection Detail Sequence": "NUMBER",
        "To Company Code": "VARCHAR2",
        "Third Party Company Code": "VARCHAR2",
        "Reversal Scope": "VARCHAR2",
        "Accounts Payable Document Type": "VARCHAR2",
        "Icn Number": "VARCHAR2",
        "Modified By Standard Flag": "VARCHAR2",
        "Consigned Quantity": "NUMBER",
        "Consigned Reversed Quantity": "NUMBER",
        "Portal Packslip Line": "VARCHAR2",
        "Received Amount": "NUMBER",
        "Unvouched Amount": "NUMBER",
        "Voucher Amount": "NUMBER",
        "Received Amount Home": "NUMBER",
        "Unvouched Amount Home": "NUMBER",
        "Voucher Amount Home": "NUMBER",
    },
},

}
